apiVersion: v1
kind: Service
metadata:
  name: {{ template "distributor.fullname" . }}
  labels:
    {{- include "distributor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: {{ .Values.config.http_listen_port }}
    protocol: TCP
    targetPort: http-metrics
  - name: grpc
    port: 9095
    protocol: TCP
    targetPort: grpc
  selector:
    {{- include "distributor.matchLabels" . | nindent 4 }}
