apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.config.http_listen_port }}
    protocol: TCP
    targetPort: http
  selector:
    {{- include "gateway.matchLabels" . | nindent 4 }}
