apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;
    events {
      worker_connections  4096;  ## Default: 1024
    }
    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;
      server {
        listen               80;
        auth_basic           “Prometheus”;
        auth_basic_user_file /etc/nginx/secrets/.htpasswd;
        proxy_set_header     X-Scope-OrgID 1;
        location = /api/prom/push {
          proxy_pass       http://{{ template "distributor.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
        }
        location = /api/prom/tail {
          proxy_pass       http://{{ template "querier.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        location ~ /api/prom/.* {
          proxy_pass       http://{{ template "query_frontend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
        }
        location = /loki/api/v1/push {
          proxy_pass       http://{{ template "distributor.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
        }
        location = /loki/api/v1/tail {
          proxy_pass       http://{{ template "querier.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }
        location ~ /loki/api/.* {
          proxy_pass       http://{{ template "query_frontend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.config.http_listen_port }}$request_uri;
        }
      }
    }
