apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
type: Opaque
data:
  .htpasswd: {{ .Values.config.htpasswd_contents | b64enc }}
