apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "querier.fullname" . }}
  labels:
    {{- include "querier.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.querier.replicaCount }}
  selector:
    matchLabels:
      {{- include "querier.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "querier.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: "querier"
        image: "{{ .Values.querier.image.repository }}:{{ .Values.querier.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.querier.image.pullPolicy }}
        args:
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/config/overrides.yaml
        - -target=querier
        - -querier.frontend-address={{ .Release.Name }}-query-frontend.{{ .Release.Namespace }}.svc.cluster.local:9095
        resources:
{{ toYaml .Values.querier.resources | indent 10 }}
        volumeMounts:
        - name: loki
          mountPath: /etc/loki/config
          readOnly: true
        ports:
        - name: http-metrics
          containerPort: {{ .Values.config.http_listen_port }}
        - name: grpc
          containerPort: 9095
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 15
          periodSeconds: 15
{{- if .Values.querier.affinity }}
      affinity:
{{ tpl .Values.querier.affinity . | indent 8 }}
{{- end }}
      volumes:
      - name: loki
        configMap:
          name: {{ template "fullname" . }}
