apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "table_manager.fullname" . }}
  labels:
    {{- include "table_manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.table_manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "table_manager.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "table_manager.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: "table-manager"
        image: "{{ .Values.table_manager.image.repository }}:{{ .Values.table_manager.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.table_manager.image.pullPolicy }}
        args:
        - -config.file=/etc/loki/config/config.yaml
        - -limits.per-user-override-config=/etc/loki/config/overrides.yaml
        - -target=table-manager
        resources:
{{ toYaml .Values.table_manager.resources | indent 10 }}
        volumeMounts:
        - name: loki
          mountPath: /etc/loki/config
          readOnly: true
        ports:
        - name: http-metrics
          containerPort: {{ .Values.config.http_listen_port }}
        - name: grpc
          containerPort: 9095
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: loki
        configMap:
          name: {{ template "fullname" . }}
