apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: "promxy"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
        args:
        - "--config=/etc/promxy/config.yaml"
        - "--web.enable-lifecycle"
        - "--log-level=warning"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/promxy/
          readOnly: true
        ports:
        - name: http
          containerPort: 8082
        readinessProbe:
          httpGet:
            path: /graph
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /graph
            port: http
          initialDelaySeconds: 5
          periodSeconds: 15

      volumes:
      - name: config-volume
        configMap:
          name: {{ template "fullname" . }}
